site_name: 项目名称

theme:
  name: material
  langage: zh
  features:
  - search.highlight
  - navigation.sections
  - navigation.top
  - navigation.tabs
  - navigation.tracking # 锚点导航
  #    - content.tabs.link     # 链接的内容选项卡
  palette: # 主题模式切换。
  - media: "(prefers-color-scheme: light)" # 跟随系统主题模式
    scheme: default
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/weather-night
      name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
- footnotes
- admonition
- pymdownx.details
- pymdownx.superfences
- pymdownx.tabbed
- pymdownx.caret
- pymdownx.mark
- pymdownx.tilde
- attr_list
- md_in_html
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets

# repo_url: https://github.com/pyloong/pythonic-project-guidelines
# repo_name: pyloong/pythonic-project-guidelines
# site_url: https://pyloong.github.io/pythonic-project-guidelines/

plugins:
- search

nav:
- 文档说明: index.md
- 项目需求: requirements.md
- 会议记录: meetings.md
- 任务调研: research.md
- 技术文档: tech.md
- 部署文档: deploy.md
- 使用文档: usage.md


# - 应用开发实践:
#   - 初级教程:
#     - 项目说明: guidelines/tutorial/tutorial.md
#     - 初始化: guidelines/tutorial/init_project.md

